[package]
name = "rustmo"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"

yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }

[dependencies.web-sys]
version = "0.3"
features = ["Window"]
